version: '3.9'
services:
  bruhbot:
    container_name: bruhbot-dev
    build: ../
    volumes: 
      - ../build:/app/build
      - data:/app/data
    environment:
      - TOKEN=$TOKEN
      - CLIENT_ID=$CLIENT_ID
      - SAD_RATE=$SAD_RATE
      - BOT_USER_ID=$BOT_USER_ID
volumes:
  data: