### GET /ping
GET http://localhost:5000/ping
Content-Type: text/plain

### POST /
POST http://localhost:5000/
Content-Type: application/json

{
	"messages": [
		{"author": "a", "content": "one"},
		{"author": "b", "content": "two"},
		{"author": "a", "content": "three"},
	]
}