name: Branch Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Repository Variable to Lowercase
      id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}
    - name: Login to GitHub Packages
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Bruhbot Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ghcr.io/${{ steps.string.outputs.lowercase }}:latest
    - name: Build and push Bruhbot Objection Engine Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./objection-engine
        push: false
        tags: ghcr.io/${{ steps.string.outputs.lowercase }}-objection-engine:latest
